default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: chefly_development

test:
  <<: *default
  database: chefly_test

production:
  <<: *default
  database: chefly_production