# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe4e9b0d72c249d68b175ec3928df0d11acb9eb306dab36f30a089cb57cd9c750241e0d5c5f540480edbf888df1999b08a7fad6c46ab0b0cd4bb9a34b75b4de0

test:
  secret_key_base: 452e81a6e95bf85b02ed015b1cf46e1970e43280a2a871e17faf98bc70a98f3c96d61ab62208efd6dc5b422eaef15c2767cdf601646a7e24718a2c752a63832c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>